networks:
  mysql-net: {}
  proxy-net: {}

volumes:
  mysql-vol: {}

services:

  mysql:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
    networks:
      - mysql-net
    # # Mount port for dev tools
    # ports:
    #   - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql-vol:/var/lib/mysql
      # # For initial database
      # - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=$$MYSQL_ROOT_PASSWORD mysqladmin ping -h localhost -u root -s"]
      start_period: 15s
      interval: 3s
      timeout: 3s
      retries: 5

  wordpress:
    image: wordpress_app
    container_name: wordpress
    build:
      context: ./docker/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_NAME:      ${MYSQL_DATABASE}
      WORDPRESS_DB_USER:      ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD:  ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST:      mysql
      WORDPRESS_DB_CHARSET:   utf8
      # WORDPRESS_DB_COLLATE:
      WORDPRESS_TABLE_PREFIX: wp_
      # WORDPRESS_AUTH_KEY:
      # WORDPRESS_SECURE_AUTH_KEY:
      # WORDPRESS_LOGGED_IN_KEY:
      # WORDPRESS_NONCE_KEY:
      # WORDPRESS_AUTH_SALT:
      # WORDPRESS_SECURE_AUTH_SALT:
      # WORDPRESS_LOGGED_IN_SALT:
      # WORDPRESS_NONCE_SALT:
      WORDPRESS_DEBUG:     1
    networks:
      - mysql-net
      - proxy-net
    restart: unless-stopped
    volumes:
      - ./docker/wordpress/php.ini:/usr/local/etc/php/conf.d/dev.ini:ro
      - ./app:/var/www/html

  web:
    image: nginx:stable-alpine
    container_name: web
    depends_on:
      - wordpress
    environment:
      PHP_FPM_ENDPOINT: wordpress:9000
    networks:
      - proxy-net
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./app:/var/www/html:ro
    healthcheck:
      test: ["CMD", "curl", "-fs", "-o", "/dev/null", "http://localhost:80/_health/nginx"]
      start_period: 15s
      interval: 5s
      timeout: 3s
      retries: 5
